// Code generated by tygo. DO NOT EDIT.
import type * as cosmoflare from "./cosmoflare.gen";

//////////
// source: metrics.go

/**
 * MetricsSnapshot is one poll of account state. Sources that fail leave
 * their field unset and carry the error message in Errors — a partial
 * snapshot publishes instead of no snapshot.
 * The data fields are the daemon's wire contract (FEAT-042): concrete
 * types, mirrored to TypeScript via make wire-types.
 */
export interface MetricsSnapshot {
  profile: string;
  collected_at: unknown /* time.Time */;
  zones?: (unknown /* cosmoflare.Zone */ | undefined)[];
  r2_buckets?: (unknown /* cosmoflare.Bucket */ | undefined)[];
  workers?: (unknown /* cosmoflare.Worker */ | undefined)[];
  kv_namespaces?: (unknown /* cosmoflare.KVNamespace */ | undefined)[];
  errors?: { [key: string]: string};
}
export interface MetricsProducer {
}

//////////
// source: rest.go

/**
 * AccountProfile is one local config profile in the /accounts response.
 * The wire shape is {"name": "<profile>"} — identical to the map the
 * adapter produced before this type existed (FEAT-042).
 */
export interface AccountProfile {
  name: string;
}
/**
 * ServeSource is the daemon's data-access seam. It is a NEW abstraction for the
 * desktop daemon — it is NOT internal/tui.DataSource (which is R2-storage-only).
 * Injecting it lets the REST handlers be unit-tested with no live Cloudflare
 * credentials: tests pass a fake, the daemon passes an adapter over the real
 * per-service constructors (see cmd/serve.go).
 * Wire contract (FEAT-042): every method returns a CONCRETE type. The JSON
 * encoding of these types IS the daemon's wire format; desktop/src/api
 * consumes TypeScript types generated from them (see the tygo config +
 * make wire-types-check). Renaming a field here breaks the desktop build,
 * not runtime.
 * Account model (v1, read-only): an "account" is a local config profile. The CF
 * methods take a profile name (empty = current/default profile) so the daemon
 * re-resolves credentials per request. There is no write-side "switch".
 */
export type ServeSource = unknown;

//////////
// source: server.go
/*
Package server implements the local HTTP+SSE daemon that powers the
Cosmoflare desktop app. It is a thin transport over the existing per-service
constructors in pkg/cosmoflare — it owns no Cloudflare logic of its own.

The desktop shell (Tauri/Rust) spawns the `cosmoflare serve` command, parses
the stdout handshake for the bound address + auth token, and drives the UI
against this server's REST + SSE endpoints.
*/

/**
 * Config holds the immutable configuration for a Server.
 */
export interface Config {
  /**
   * Token is the bearer token required on every request (Authorization:
   * Bearer <token>). The shell generates a random token and passes it both
   * to the daemon and to the webview.
   */
  Token: string;
  /**
   * Version is reported in /healthz and the handshake. Usually AppVersion.
   */
  Version: string;
}
/**
 * Server is the daemon's HTTP server. It is safe for concurrent use: REST
 * handlers flip cfOnline from many goroutines and the SSE hub is mutex-guarded.
 */
export interface Server {
}

//////////
// source: sse.go

/**
 * SSE channel names. These are a wire contract shared by this package's
 * producers, the serve daemon's glue code (cmd/serve.go), and the desktop
 * client — publish and subscribe through these constants, never literals,
 * so a rename cannot silently orphan one side.
 */
export const ChannelMetrics = "metrics";
/**
 * SSE channel names. These are a wire contract shared by this package's
 * producers, the serve daemon's glue code (cmd/serve.go), and the desktop
 * client — publish and subscribe through these constants, never literals,
 * so a rename cannot silently orphan one side.
 */
export const ChannelNotifications = "notifications";
/**
 * SSE channel names. These are a wire contract shared by this package's
 * producers, the serve daemon's glue code (cmd/serve.go), and the desktop
 * client — publish and subscribe through these constants, never literals,
 * so a rename cannot silently orphan one side.
 */
export const ChannelStatus = "status";
