// Code generated by tygo. DO NOT EDIT.

//////////
// source: kv.go

/**
 * KVNamespace represents a Cloudflare Workers KV namespace.
 */
export interface KVNamespace {
  id: string;
  title: string;
}
/**
 * KVKey represents a key in a KV namespace.
 */
export interface KVKey {
  key: string;
  expiration?: number /* int64 */;
}
/**
 * KVOption is a functional option for KV write operations.
 */
export type KVOption = unknown;
/**
 * KVListOption is a functional option for KV list operations.
 */
export type KVListOption = unknown;
/**
 * KVService implements KV operations.
 */
export interface KVService {
}

//////////
// source: types.go
/*
Package cosmoflare — see doc.go for the package documentation.
*/

/**
 * Bucket represents a Cloudflare R2 bucket.
 */
export interface Bucket {
  name: string;
  created_at: string /* RFC3339 */;
  location?: string;
  storage?: string;
  size: number /* int64 */;
  object_count: number /* int64 */;
  tags?: { [key: string]: string};
}
/**
 * Object represents an object stored in an R2 bucket.
 */
export interface Object {
  key: string;
  size: number /* int64 */;
  last_modified: string /* RFC3339 */;
  etag: string;
  storage_class: string;
  content_type?: string;
  metadata?: { [key: string]: string};
}
/**
 * UploadResult contains the result of an upload operation.
 */
export interface UploadResult {
  key: string;
  bucket: string;
  size: number /* int64 */;
  etag: string;
  version_id?: string;
  uploaded: string /* RFC3339 */;
  parts?: number /* int */;
}
/**
 * DownloadResult contains the result of a download operation.
 */
export interface DownloadResult {
  key: string;
  bucket: string;
  size: number /* int64 */;
  Content: unknown /* io.ReadCloser */;
  content_type?: string;
  metadata?: { [key: string]: string};
}
/**
 * ListResult is a generic paginated list result.
 */
export interface ListResult<T extends unknown> {
  items: T[];
  next_token?: string;
  is_truncated: boolean;
  common_prefixes?: string[];
}
/**
 * CopyResult contains the result of a copy operation.
 */
export interface CopyResult {
  key: string;
  source_key: string;
  bucket: string;
  etag: string;
  version_id?: string;
}
/**
 * HeadResult contains object metadata without the body.
 */
export interface HeadResult {
  key: string;
  size: number /* int64 */;
  last_modified: string /* RFC3339 */;
  etag: string;
  content_type?: string;
  cache_control?: string;
  metadata?: { [key: string]: string};
}

//////////
// source: worker.go

/**
 * Worker represents a Cloudflare Worker script.
 */
export interface Worker {
  name: string;
  modified: string /* RFC3339 */;
  size: number /* int64 */;
  runtime: string;
  bindings?: WorkerBinding[];
  tags?: string[];
  script?: string;
  compatibility_date?: string;
}
/**
 * WorkerBinding represents a binding attached to a Worker.
 */
export interface WorkerBinding {
  name: string;
  type: string; // "kv", "r2", "d1", "queue", "var", "secret_text"
  id: string;
}
/**
 * WorkerSettings holds configurable Worker settings.
 */
export interface WorkerSettings {
  compatibility_date: string;
  usage_model: string; // "bundled" or "unbound"
  bindings?: WorkerBinding[];
}
/**
 * LogEntry represents a single Worker log event.
 */
export interface LogEntry {
  timestamp: string /* RFC3339 */;
  level: string;
  message: string;
  event: string;
}
/**
 * WorkerOption is a functional option for Worker operations.
 */
export type WorkerOption = unknown;
/**
 * LogOption is a functional option for log retrieval.
 */
export type LogOption = unknown;
/**
 * WorkerService implements WorkerService.
 */
export interface WorkerService {
}
/**
 * TailOptions configures the TailLogs polling loop.
 */
export interface TailOptions {
  Interval: number /* ns */;
  Level: string;
  Since: number /* ns */;
}

//////////
// source: zone.go

/**
 * Zone represents a Cloudflare DNS zone.
 */
export interface Zone {
  id: string;
  name: string;
  status: string;
  type: string;
  paused: boolean;
  name_servers: string[];
  original_name_servers?: string[];
  plan: ZonePlan;
  created_on: string /* RFC3339 */;
  modified_on: string /* RFC3339 */;
}
/**
 * ZonePlan contains the plan information for a zone.
 */
export interface ZonePlan {
  id: string;
  legacy_id?: string; // "free" | "pro" | "business" | "enterprise"
  name: string;
}
/**
 * ZoneSetting contains a single zone setting entry.
 */
export interface ZoneSetting {
  id: string;
  value: unknown;
  editable: boolean;
  modified_on?: string;
}
/**
 * ZoneService implements zone management operations.
 */
export interface ZoneService {
}
