// Code generated by tygo. DO NOT EDIT.
import type * as cosmoflare from "./cosmoflare.gen";

//////////
// source: metrics.go

/**
 * MetricsSnapshot is one poll of account state. Sources that fail leave
 * their field unset and carry the error message in Errors — a partial
 * snapshot publishes instead of no snapshot.
 * The data fields are the daemon's wire contract (FEAT-042): concrete
 * types, mirrored to TypeScript via make wire-types.
 */
export interface MetricsSnapshot {
  profile: string;
  collected_at: string /* RFC3339 */;
  zones?: (cosmoflare.Zone | undefined)[];
  r2_buckets?: (cosmoflare.Bucket | undefined)[];
  workers?: (cosmoflare.Worker | undefined)[];
  kv_namespaces?: (cosmoflare.KVNamespace | undefined)[];
  errors?: { [key: string]: string};
}
export interface MetricsProducer {
}

//////////
// source: rest.go

/**
 * AccountProfile is one local config profile in the /accounts response.
 * The wire shape is {"name": "<profile>"} — identical to the map the
 * adapter produced before this type existed (FEAT-042).
 */
export interface AccountProfile {
  name: string;
}
/**
 * ServeSource is the daemon's data-access seam. It is a NEW abstraction for the
 * desktop daemon — it is NOT internal/tui.DataSource (which is R2-storage-only).
 * Injecting it lets the REST handlers be unit-tested with no live Cloudflare
 * credentials: tests pass a fake, the daemon passes an adapter over the real
 * per-service constructors (see cmd/serve.go).
 * Wire contract (FEAT-042): every method returns a CONCRETE type. The JSON
 * encoding of these types IS the daemon's wire format; desktop/src/api
 * consumes TypeScript types generated from them (see the tygo config +
 * make wire-types-check). Renaming a field here breaks the desktop build,
 * not runtime.
 * Account model (v1, read-only): an "account" is a local config profile. The CF
 * methods take a profile name (empty = current/default profile) so the daemon
 * re-resolves credentials per request. There is no write-side "switch".
 */
export type ServeSource = unknown;
