package cosmoflare

import (
	"strings"
	"testing"
)

func TestGenerateWorkerTypesEveryKind(t *testing.T) {
	settings := WorkerSettings{
		CompatibilityDate: "2026-01-01",
		Bindings: []WorkerBinding{
			{Name: "MY_KV", Type: "kv", ID: "ns-1"},
			{Name: "MY_R2", Type: "r2", ID: "bucket-1"},
			{Name: "MY_D1", Type: "d1", ID: "db-1"},
			{Name: "MY_QUEUE", Type: "queue", ID: "q-1"},
			{Name: "MY_VAR", Type: "var", ID: "value"},
			{Name: "MY_SECRET", Type: "secret_text", ID: "s3cret"},
		},
	}
	out := GenerateWorkerTypes(settings)

	for _, want := range []string{
		"// Generated by cosmoflare worker types — do not edit.",
		"declare interface KVNamespace { get(key: string): Promise<string | null>;",
		"declare interface R2Bucket { get(key: string): Promise<R2Object | null>;",
		"declare interface D1Database { prepare(query: string): D1PreparedStatement }",
		"declare interface Queue<T = unknown> { send(message: T): Promise<void> }",
		"declare interface Fetcher { fetch(input: RequestInfo, init?: RequestInit): Promise<Response> }",
		"  MY_KV: KVNamespace;",
		"  MY_R2: R2Bucket;",
		"  MY_D1: D1Database;",
		"  MY_QUEUE: Queue;",
		"  MY_VAR: string;",
		"  MY_SECRET: string;",
		"export { Env, KVNamespace, R2Bucket, R2Object, D1Database, D1PreparedStatement, Queue, Fetcher };",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("expected output to contain %q\noutput:\n%s", want, out)
		}
	}
}

func TestGenerateWorkerTypesSorted(t *testing.T) {
	settings := WorkerSettings{
		Bindings: []WorkerBinding{
			{Name: "ZULU", Type: "var", ID: "z"},
			{Name: "ALPHA", Type: "kv", ID: "a"},
			{Name: "MIKE", Type: "r2", ID: "m"},
		},
	}
	out := GenerateWorkerTypes(settings)
	if strings.Index(out, "  ALPHA:") > strings.Index(out, "  MIKE:") ||
		strings.Index(out, "  MIKE:") > strings.Index(out, "  ZULU:") {
		t.Errorf("bindings not emitted in sorted name order:\n%s", out)
	}

	// Stability: same input, same output.
	if out != GenerateWorkerTypes(settings) {
		t.Error("generator output is not stable for identical input")
	}
}

func TestGenerateWorkerTypesZeroBindings(t *testing.T) {
	out := GenerateWorkerTypes(WorkerSettings{})
	if !strings.Contains(out, "// Generated by cosmoflare worker types — do not edit.") {
		t.Error("expected do-not-edit header in zero-binding output")
	}
	if !strings.Contains(out, "interface Env {\n}") {
		t.Errorf("expected an empty Env interface, got:\n%s", out)
	}
	if !strings.Contains(out, "export { Env, KVNamespace, R2Bucket, R2Object, D1Database, D1PreparedStatement, Queue, Fetcher };") {
		t.Error("expected export line in zero-binding output")
	}
}

func TestWorkerSettingsRawBindingToWorkerBinding(t *testing.T) {
	cases := []struct {
		raw  workerSettingsRawBinding
		want WorkerBinding
	}{
		{workerSettingsRawBinding{Type: "kv", Name: "KV", NamespaceID: "ns-9"}, WorkerBinding{Name: "KV", Type: "kv", ID: "ns-9"}},
		{workerSettingsRawBinding{Type: "r2_bucket", Name: "R2", BucketName: "bkt"}, WorkerBinding{Name: "R2", Type: "r2", ID: "bkt"}},
		{workerSettingsRawBinding{Type: "d1", Name: "D1", ID: "db"}, WorkerBinding{Name: "D1", Type: "d1", ID: "db"}},
		{workerSettingsRawBinding{Type: "queue", Name: "Q", QueueName: "q"}, WorkerBinding{Name: "Q", Type: "queue", ID: "q"}},
		{workerSettingsRawBinding{Type: "plain_text", Name: "V", Text: "txt"}, WorkerBinding{Name: "V", Type: "plain_text", ID: "txt"}},
		{workerSettingsRawBinding{Type: "secret_text", Name: "S"}, WorkerBinding{Name: "S", Type: "secret_text"}},
	}
	for _, tc := range cases {
		got := tc.raw.toWorkerBinding()
		if got != tc.want {
			t.Errorf("toWorkerBinding(%+v) = %+v, want %+v", tc.raw, got, tc.want)
		}
	}
}
