package cosmoflare

import (
	"context"
	"fmt"
	"sort"
	"strings"
)

// Worker types .d.ts generator (FEAT-021 wave 3).
//
// GenerateWorkerTypes is a PURE function: it renders the
// worker-configuration.d.ts content for a set of WorkerSettings. No
// network I/O happens here — callers fetch settings themselves
// (SettingsGet below, or a locally built WorkerSettings).

// workerTypesInterfaces is the constant prologue of every generated file:
// the do-not-edit header plus the ambient runtime interface declarations.
func workerTypesInterfaces() string {
	return `// Generated by cosmoflare worker types — do not edit.
declare interface KVNamespace { get(key: string): Promise<string | null>; put(key: string, value: string): Promise<void>; delete(key: string): Promise<void>; list(): Promise<{ keys: string[] }> }
declare interface R2Bucket { get(key: string): Promise<R2Object | null>; put(key: string, value: BodyInit): Promise<R2Object>; delete(key: string): Promise<void> }
declare interface R2Object { key: string; size: number; uploaded: string }
declare interface D1Database { prepare(query: string): D1PreparedStatement }
declare interface D1PreparedStatement { bind(...values: unknown[]): D1PreparedStatement; first<T = unknown>(): Promise<T>; all<T = unknown>(): Promise<T[]>; run(): Promise<unknown> }
declare interface Queue<T = unknown> { send(message: T): Promise<void> }
declare interface Fetcher { fetch(input: RequestInfo, init?: RequestInit): Promise<Response> }
`
}

// GenerateWorkerTypes renders a complete worker-configuration.d.ts for the
// given settings. Bindings are emitted sorted by name so output is stable;
// a settings value with zero bindings still produces the header and an
// empty Env interface. Unknown binding kinds fall back to string.
func GenerateWorkerTypes(settings WorkerSettings) string {
	bindings := make([]WorkerBinding, len(settings.Bindings))
	copy(bindings, settings.Bindings)
	sort.Slice(bindings, func(i, j int) bool { return bindings[i].Name < bindings[j].Name })

	var b strings.Builder
	b.WriteString(workerTypesInterfaces())
	b.WriteString("\ninterface Env {\n")
	for _, binding := range bindings {
		fmt.Fprintf(&b, "  %s: %s;\n", binding.Name, workerBindingTSType(binding.Type))
	}
	b.WriteString("}\n\nexport { Env, KVNamespace, R2Bucket, R2Object, D1Database, D1PreparedStatement, Queue, Fetcher };\n")
	return b.String()
}

// workerBindingTSType maps a WorkerBinding.Type to its TypeScript type name.
func workerBindingTSType(bindingType string) string {
	switch bindingType {
	case "kv":
		return "KVNamespace"
	case "r2":
		return "R2Bucket"
	case "d1":
		return "D1Database"
	case "queue":
		return "Queue"
	default:
		// "var", "secret_text", and anything unrecognized.
		return "string"
	}
}

// SettingsGet fetches a Worker's current settings (compatibility date,
// usage model, bindings) from the script-settings REST endpoint.
// cloudflare-go v0.116 exposes no bindings in its settings response, so
// this goes through rawRequest and therefore requires credentials-based
// construction (NewWorkerServiceFromCreds).
func (s *WorkerService) SettingsGet(ctx context.Context, name string) (WorkerSettings, error) {
	if name == "" {
		return WorkerSettings{}, validationError("WorkerService.SettingsGet", "worker name is required")
	}

	var result struct {
		CompatibilityDate string                     `json:"compatibility_date"`
		UsageModel        string                     `json:"usage_model"`
		Bindings          []workerSettingsRawBinding `json:"bindings"`
	}
	path := fmt.Sprintf("/accounts/%s/workers/scripts/%s/settings", s.accountID, name)
	if err := s.rawRequest(ctx, "GET", path, nil, &result); err != nil {
		return WorkerSettings{}, newError("WorkerService.SettingsGet", fmt.Sprintf("failed to fetch settings for worker %q", name), err)
	}

	bindings := make([]WorkerBinding, 0, len(result.Bindings))
	for _, rb := range result.Bindings {
		bindings = append(bindings, rb.toWorkerBinding())
	}
	return WorkerSettings{
		CompatibilityDate: result.CompatibilityDate,
		UsageModel:        result.UsageModel,
		Bindings:          bindings,
	}, nil
}

// workerSettingsRawBinding mirrors the per-type field layout the settings
// endpoint uses: the resource identifier lives in a type-specific field
// (namespace_id, bucket_name, queue_name, text, id).
type workerSettingsRawBinding struct {
	Type        string `json:"type"`
	Name        string `json:"name"`
	ID          string `json:"id"`
	NamespaceID string `json:"namespace_id"`
	BucketName  string `json:"bucket_name"`
	QueueName   string `json:"queue_name"`
	Text        string `json:"text"`
}

// toWorkerBinding normalizes an API binding into our generic shape.
// The API reports R2 buckets as "r2_bucket"; we normalize to "r2" to match
// the binding vocabulary used by toCFBindings in worker.go.
func (b workerSettingsRawBinding) toWorkerBinding() WorkerBinding {
	bindingType := b.Type
	if bindingType == "r2_bucket" {
		bindingType = "r2"
	}
	id := b.ID
	if id == "" {
		for _, v := range []string{b.NamespaceID, b.BucketName, b.QueueName, b.Text} {
			if v != "" {
				id = v
				break
			}
		}
	}
	return WorkerBinding{Name: b.Name, Type: bindingType, ID: id}
}
