package alertspush

import (
	"context"
	"fmt"
	"io"
	"net/http"

	"github.com/SherClockHolmes/webpush-go"
)

// Sender delivers one push envelope to one subscription and reports the HTTP
// status the push service answered with. status is 0 when the delivery failed
// before an HTTP response existed (e.g. transport error).
type Sender interface {
	Send(ctx context.Context, sub Subscription, envelope []byte) (status int, err error)
}

// vapidSubscriber is the contact URI presented in the VAPID JWT sub claim.
// Push services require a mailto: or https: contact for abuse reports.
const vapidSubscriber = "mailto:alerts@cosmolabs.org"

// pushTTL is how long push services may keep an undelivered alert (1 hour).
// Alerts are time-sensitive; there is little value in a stale wake-up.
const pushTTL = 3600

// WebPushSender is the production Sender: it delivers envelopes with the Web
// Push protocol (VAPID auth) via webpush-go.
type WebPushSender struct {
	publicKey  string
	privateKey string
	subscriber string
	client     *http.Client
}

var _ Sender = (*WebPushSender)(nil)

// NewWebPushSender returns a Sender authenticating pushes with the given
// VAPID keypair (base64url raw form, as generated by Store.Keygen).
func NewWebPushSender(publicKey, privateKey string) *WebPushSender {
	return &WebPushSender{
		publicKey:  publicKey,
		privateKey: privateKey,
		subscriber: vapidSubscriber,
	}
}

// Send delivers envelope to sub and returns the push service's HTTP status.
func (w *WebPushSender) Send(ctx context.Context, sub Subscription, envelope []byte) (int, error) {
	wpSub := &webpush.Subscription{
		Endpoint: sub.Endpoint,
		Keys: webpush.Keys{
			P256dh: sub.P256dh,
			Auth:   sub.Auth,
		},
	}
	opts := &webpush.Options{
		Subscriber:      w.subscriber,
		VAPIDPublicKey:  w.publicKey,
		VAPIDPrivateKey: w.privateKey,
		TTL:             pushTTL,
	}
	if w.client != nil {
		opts.HTTPClient = w.client
	}
	resp, err := webpush.SendNotificationWithContext(ctx, envelope, wpSub, opts)
	if err != nil {
		return 0, fmt.Errorf("web push %s: %w", sub.Endpoint, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		_, _ = io.Copy(io.Discard, resp.Body) // drain so the connection can be reused
	}
	return resp.StatusCode, nil
}

// Dispatch pushes p to every subscription in st. Expired endpoints (HTTP
// 404/410 from the push service) are removed from the store and counted in
// pruned. One failing subscription never aborts the rest; the first
// non-prune error is returned. sent counts successful deliveries.
func Dispatch(ctx context.Context, st *Store, sender Sender, p Payload) (sent, pruned int, err error) {
	envelope, err := p.MarshalEnvelope()
	if err != nil {
		return 0, 0, err
	}
	var firstErr error
	for _, sub := range st.Subscriptions {
		status, sendErr := sender.Send(ctx, sub, envelope)
		if status == http.StatusNotFound || status == http.StatusGone {
			// The endpoint is permanently gone (expired or revoked):
			// prune it from the store instead of erroring.
			st.RemoveSubscription(sub.Endpoint)
			pruned++
			continue
		}
		if sendErr != nil {
			if firstErr == nil {
				firstErr = fmt.Errorf("web push %s: %w", sub.Endpoint, sendErr)
			}
			continue
		}
		if status >= 200 && status < 300 {
			sent++
			continue
		}
		if firstErr == nil {
			firstErr = fmt.Errorf("web push %s: unexpected status %d", sub.Endpoint, status)
		}
	}
	return sent, pruned, firstErr
}
