package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var (
	initYes      bool
	initTemplate string
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize a new Cosmoflare project",
	Long: `Scaffold a new Cosmoflare project in the current directory.

Detects your framework (Wrangler, Go, Node) and generates a .cosmoflare.yaml
configuration file with sensible defaults.

Use --yes (-y) for non-interactive CI mode with defaults.

Templates:
  worker  — Cloudflare Worker project
  pages   — Cloudflare Pages static site
  r2      — R2 storage-focused project
  full    — All services enabled

Examples:
  cosmoflare init                     # Interactive setup
  cosmoflare init --yes               # Non-interactive with defaults
  cosmoflare init --template worker   # Worker project template
  cosmoflare init --template full -y  # Full project, no prompts
  cosmoflare init --json              # Machine-readable output`,
	Args: cobra.NoArgs,
	RunE: runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)

	initCmd.Flags().BoolVarP(&initYes, "yes", "y", false, "Non-interactive mode with sensible defaults")
	initCmd.Flags().StringVar(&initTemplate, "template", "", "Project template: worker|pages|r2|full (default: auto-detect)")
}

var configTemplates = map[string]string{
	"worker": `# Cosmoflare Project Configuration
# Generated by: cosmoflare init --template worker

name: "%s"
type: worker

workers:
  main:
    script: src/index.js
    compatibility_date: "2024-01-01"
    module: true
`,
	"pages": `# Cosmoflare Project Configuration
# Generated by: cosmoflare init --template pages

name: "%s"
type: pages

pages:
  build_command: npm run build
  build_output: dist
`,
	"r2": `# Cosmoflare Project Configuration
# Generated by: cosmoflare init --template r2

name: "%s"
type: r2

r2:
  buckets:
    - name: my-bucket
      location: auto
`,
	"full": `# Cosmoflare Project Configuration
# Generated by: cosmoflare init --template full

name: "%s"
type: full

workers:
  main:
    script: src/index.js
    compatibility_date: "2024-01-01"
    module: true

r2:
  buckets:
    - name: my-bucket
      location: auto

kv:
  namespaces: []

dns:
  zone_id: ""
`,
}

func runInit(cmd *cobra.Command, args []string) error {
	dir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	template := initTemplate
	if template == "" {
		template = detectTemplate(dir)
	}

	force := false
	err = scaffoldProject(dir, template, force)
	if err != nil {
		return err
	}

	if JSONOutput {
		return printJSON(map[string]interface{}{
			"success":  true,
			"message":  "Project initialized",
			"template": template,
			"config":   ".cosmoflare.yaml",
		})
	}

	fmt.Fprintf(cmd.OutOrStdout(), "✅ Cosmoflare project initialized with template: %s\n", template)
	fmt.Fprintf(cmd.OutOrStdout(), "   Config: %s\n", filepath.Join(dir, ".cosmoflare.yaml"))
	return nil
}

func scaffoldProject(dir string, template string, force bool) error {
	configPath := filepath.Join(dir, ".cosmoflare.yaml")

	if !force {
		if _, err := os.Stat(configPath); err == nil {
			return fmt.Errorf(".cosmoflare.yaml already exists in %s (use --force or delete it first)", dir)
		}
	}

	tmpl, ok := configTemplates[template]
	if !ok {
		tmpl = configTemplates["worker"]
	}

	projectName := filepath.Base(dir)
	content := fmt.Sprintf(tmpl, projectName)

	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write .cosmoflare.yaml: %w", err)
	}

	return nil
}

func detectTemplate(dir string) string {
	if _, err := os.Stat(filepath.Join(dir, "wrangler.toml")); err == nil {
		return "worker"
	}
	if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
		return "full"
	}
	if _, err := os.Stat(filepath.Join(dir, "package.json")); err == nil {
		return "pages"
	}
	return "worker"
}
