package cmdmanifest

// registry is the command registry in declaration order. Wave 1 authors the
// r2 pilot group (FEAT-020); later waves append groups without touching the
// loader. Permissions come from the live token-UI names verified 2026-09-18
// (docs/research/2026-09-17-cf-perms-next-waves-tiers/qwen-results.md);
// entries left empty await the FEAT-011 dataset, never "none required".
var registry = []Command{
	// --- r2 bucket lifecycle ---
	{
		ID: "r2.bucket.create", CLIPath: []string{"r2", "bucket", "create"},
		WranglerEquivalent: "wrangler r2 bucket create",
		Service: "r2", Scope: "account", Verb: "write",
		APIOps:      []string{"POST /accounts/{account_id}/r2/buckets"},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		Limits:      []string{"r2.buckets"},
		LocalChecks: []string{"name_charset"},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest"},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "r2.bucket.list", CLIPath: []string{"r2", "bucket", "list"},
		WranglerEquivalent: "wrangler r2 bucket list",
		Service: "r2", Scope: "account", Verb: "list",
		APIOps:      []string{"GET /accounts/{account_id}/r2/buckets"},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest"},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "r2.bucket.get", CLIPath: []string{"r2", "bucket", "get"},
		WranglerEquivalent: "wrangler r2 bucket info",
		Service: "r2", Scope: "bucket", Verb: "read",
		APIOps:      []string{"GET /accounts/{account_id}/r2/buckets/{bucket}"},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest"},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "r2.bucket.exists", CLIPath: []string{"r2", "bucket", "exists"},
		Service: "r2", Scope: "bucket", Verb: "read",
		APIOps:      []string{"HEAD /accounts/{account_id}/r2/buckets/{bucket}"},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest"},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "r2.bucket.delete", CLIPath: []string{"r2", "bucket", "delete"},
		WranglerEquivalent: "wrangler r2 bucket delete",
		Service: "r2", Scope: "bucket", Verb: "delete",
		APIOps:      []string{"DELETE /accounts/{account_id}/r2/buckets/{bucket}"},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		APIChecks:   []string{"bucket_empty"},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest"},
		DangerLevel: "high", Destructive: true, Trackable: true,
	},

	// --- r2 object operations ---
	{
		ID: "r2.object.put", CLIPath: []string{"r2", "object", "put"},
		WranglerEquivalent: "wrangler r2 object put",
		Service: "r2", Scope: "object", Verb: "write",
		APIOps: []string{
			"PUT /{bucket}/{key}",
			"POST multipart-upload", "POST upload-part", "POST complete-multipart-upload",
		},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		Limits:      []string{"r2.upload_single", "r2.upload_multipart", "r2.object_metadata"},
		LocalChecks: []string{"file_size", "metadata_size", "key_length"},
		APIChecks:   []string{"bucket_exists", "api_rate_remaining"},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest_or_s3"},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "r2.object.get", CLIPath: []string{"r2", "object", "get"},
		WranglerEquivalent: "wrangler r2 object get",
		Service: "r2", Scope: "object", Verb: "read",
		APIOps:      []string{"GET /{bucket}/{key}"},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest_or_s3"},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "r2.object.delete", CLIPath: []string{"r2", "object", "delete"},
		WranglerEquivalent: "wrangler r2 object delete",
		Service: "r2", Scope: "object", Verb: "delete",
		APIOps:      []string{"DELETE /{bucket}/{key}"},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest_or_s3"},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "r2.object.list", CLIPath: []string{"r2", "object", "list"},
		Service: "r2", Scope: "bucket", Verb: "list",
		APIOps:      []string{"GET /{bucket}?list-type=2"},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest_or_s3"},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},

	// --- r2 sync / watch (workflow commands over the object surface) ---
	{
		ID: "sync.up", CLIPath: []string{"sync", "up"},
		Service: "r2", Scope: "bucket", Verb: "write",
		APIOps:      []string{"PUT /{bucket}/{key}", "POST multipart-upload"},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		Limits:      []string{"r2.upload_single", "r2.upload_multipart"},
		LocalChecks: []string{"directory_exists", "exclude_patterns"},
		APIChecks:   []string{"bucket_exists"},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest_or_s3"},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "sync.down", CLIPath: []string{"sync", "down"},
		Service: "r2", Scope: "bucket", Verb: "read",
		APIOps:      []string{"GET /{bucket}?list-type=2", "GET /{bucket}/{key}"},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		LocalChecks: []string{"destination_writable"},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest_or_s3"},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "watch", CLIPath: []string{"watch"},
		Service: "r2", Scope: "bucket", Verb: "write",
		APIOps:      []string{"PUT /{bucket}/{key}"},
		Permissions: Permissions{Account: []string{"Workers R2 Storage"}},
		LocalChecks: []string{"directory_exists"},
		RateLimit:   &RateLimitBehavior{HTTPStatus: 429, RetryAfter: true, Bucket: "r2_rest_or_s3"},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},

	// --- worker script lifecycle (wave 2; permissions from the Qwen dataset) ---
	{
		ID: "worker.deploy", CLIPath: []string{"worker", "deploy"},
		WranglerEquivalent: "wrangler deploy",
		Service: "workers", Scope: "script", Verb: "write",
		APIOps:      []string{"PUT /accounts/{account_id}/workers/scripts/{script_name}"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.list", CLIPath: []string{"worker", "list"},
		Service: "workers", Scope: "account", Verb: "list",
		APIOps:      []string{"GET /accounts/{account_id}/workers/scripts"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.get", CLIPath: []string{"worker", "get"},
		Service: "workers", Scope: "script", Verb: "read",
		APIOps:      []string{"GET /accounts/{account_id}/workers/scripts/{script_name}"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.delete", CLIPath: []string{"worker", "delete"},
		WranglerEquivalent: "wrangler delete",
		Service: "workers", Scope: "script", Verb: "delete",
		APIOps:      []string{"DELETE /accounts/{account_id}/workers/scripts/{script_name}"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		APIChecks:   []string{"script_exists"},
		DangerLevel: "high", Destructive: true, Trackable: true,
	},
	{
		ID: "worker.logs", CLIPath: []string{"worker", "logs"},
		Service: "workers", Scope: "script", Verb: "read",
		APIOps:      []string{"GET /accounts/{account_id}/workers/observability/telemetry/query"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.tail", CLIPath: []string{"worker", "tail"},
		WranglerEquivalent: "wrangler tail",
		Service: "workers", Scope: "script", Verb: "read",
		APIOps:      []string{"POST /accounts/{account_id}/workers/scripts/{script_name}/tails"},
		Permissions: Permissions{Account: []string{"Workers Tail", "Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.settings", CLIPath: []string{"worker", "settings"},
		Service: "workers", Scope: "script", Verb: "write",
		APIOps:      []string{"PATCH /accounts/{account_id}/workers/scripts/{script_name}/settings"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.bindings", CLIPath: []string{"worker", "bindings"},
		Service: "workers", Scope: "script", Verb: "read",
		APIOps:      []string{"GET /accounts/{account_id}/workers/scripts/{script_name}/settings"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.types", CLIPath: []string{"worker", "types"},
		WranglerEquivalent: "wrangler types",
		Service: "workers", Scope: "script", Verb: "read",
		APIOps:      []string{"GET /accounts/{account_id}/workers/scripts/{script_name}/settings"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		LocalChecks: []string{"bindings_present"},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.rollback", CLIPath: []string{"worker", "rollback"},
		WranglerEquivalent: "wrangler rollback",
		Service: "workers", Scope: "script", Verb: "write",
		APIOps:      []string{"POST /accounts/{account_id}/workers/scripts/{script_name}/versions/{version_id}/deploy"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},

	// --- worker cron triggers (schedules are a full-set replace server-side) ---
	{
		ID: "worker.cron.list", CLIPath: []string{"worker", "cron", "list"},
		Service: "workers", Scope: "script", Verb: "list",
		APIOps:      []string{"GET /accounts/{account_id}/workers/scripts/{script_name}/schedules"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.cron.create", CLIPath: []string{"worker", "cron", "create"},
		Service: "workers", Scope: "script", Verb: "write",
		APIOps:      []string{"PUT /accounts/{account_id}/workers/scripts/{script_name}/schedules"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.cron.update", CLIPath: []string{"worker", "cron", "update"},
		Service: "workers", Scope: "script", Verb: "write",
		APIOps:      []string{"PUT /accounts/{account_id}/workers/scripts/{script_name}/schedules"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.cron.delete", CLIPath: []string{"worker", "cron", "delete"},
		Service: "workers", Scope: "script", Verb: "delete",
		APIOps:      []string{"PUT /accounts/{account_id}/workers/scripts/{script_name}/schedules"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},

	// --- worker secrets (values are write-only; only names ever surface) ---
	{
		ID: "worker.secret.put", CLIPath: []string{"worker", "secret", "put"},
		WranglerEquivalent: "wrangler secret put",
		Service: "workers", Scope: "secret", Verb: "write",
		APIOps:      []string{"PUT /accounts/{account_id}/workers/scripts/{script_name}/secrets"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.secret.bulk", CLIPath: []string{"worker", "secret", "bulk"},
		WranglerEquivalent: "wrangler secret bulk",
		Service: "workers", Scope: "secret", Verb: "write",
		APIOps:      []string{"PUT /accounts/{account_id}/workers/scripts/{script_name}/secrets/bulk"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		LocalChecks: []string{"secrets_file_json"},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.secret.list", CLIPath: []string{"worker", "secret", "list"},
		WranglerEquivalent: "wrangler secret list",
		Service: "workers", Scope: "secret", Verb: "list",
		APIOps:      []string{"GET /accounts/{account_id}/workers/scripts/{script_name}/secrets"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.secret.delete", CLIPath: []string{"worker", "secret", "delete"},
		WranglerEquivalent: "wrangler secret delete",
		Service: "workers", Scope: "secret", Verb: "delete",
		APIOps:      []string{"DELETE /accounts/{account_id}/workers/scripts/{script_name}/secrets/{secret_name}"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},

	// --- worker domains (permission group pending the FEAT-011 dataset) ---
	{
		ID: "worker.domain.list", CLIPath: []string{"worker", "domain", "list"},
		Service: "workers", Scope: "domain", Verb: "list",
		APIOps: []string{"GET /accounts/{account_id}/workers/domains"},
		// "Workers Custom Domains" not yet in the Qwen dataset — awaiting
		// FEAT-011 ingest rather than guessing the token-UI spelling.
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.domain.attach", CLIPath: []string{"worker", "domain", "attach"},
		Service: "workers", Scope: "domain", Verb: "write",
		APIOps:      []string{"POST /accounts/{account_id}/workers/domains"},
		LocalChecks: []string{"dns_record_resolves"},
		// permission pending FEAT-011 dataset
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.domain.detach", CLIPath: []string{"worker", "domain", "detach"},
		Service: "workers", Scope: "domain", Verb: "delete",
		APIOps: []string{"DELETE /accounts/{account_id}/workers/domains/{domain_id}"},
		// permission pending FEAT-011 dataset
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},

	// --- worker routes (zone-scoped; zone permission from the Qwen dataset) ---
	{
		ID: "worker.route.list", CLIPath: []string{"worker", "route", "list"},
		Service: "workers", Scope: "route", Verb: "list",
		APIOps:      []string{"GET /zones/{zone_id}/workers/routes"},
		Permissions: Permissions{Zone: []string{"Workers Routes"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.route.create", CLIPath: []string{"worker", "route", "create"},
		Service: "workers", Scope: "route", Verb: "write",
		APIOps:      []string{"POST /zones/{zone_id}/workers/routes"},
		Permissions: Permissions{Zone: []string{"Workers Routes"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.route.update", CLIPath: []string{"worker", "route", "update"},
		Service: "workers", Scope: "route", Verb: "write",
		APIOps:      []string{"PUT /zones/{zone_id}/workers/routes/{route_id}"},
		Permissions: Permissions{Zone: []string{"Workers Routes"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.route.delete", CLIPath: []string{"worker", "route", "delete"},
		Service: "workers", Scope: "route", Verb: "delete",
		APIOps:      []string{"DELETE /zones/{zone_id}/workers/routes/{route_id}"},
		Permissions: Permissions{Zone: []string{"Workers Routes"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},

	// --- workers.dev subdomain ---
	{
		ID: "worker.subdomain.get", CLIPath: []string{"worker", "subdomain", "get"},
		Service: "workers", Scope: "account", Verb: "read",
		APIOps:      []string{"GET /accounts/{account_id}/workers/subdomain"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.subdomain.set", CLIPath: []string{"worker", "subdomain", "set"},
		Service: "workers", Scope: "account", Verb: "write",
		APIOps:      []string{"PUT /accounts/{account_id}/workers/subdomain"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		LocalChecks: []string{"subdomain_charset"},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},

	// --- worker versions & deployments ---
	{
		ID: "worker.versions.list", CLIPath: []string{"worker", "versions", "list"},
		WranglerEquivalent: "wrangler versions list",
		Service: "workers", Scope: "version", Verb: "list",
		APIOps:      []string{"GET /accounts/{account_id}/workers/scripts/{script_name}/versions"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.versions.upload", CLIPath: []string{"worker", "versions", "upload"},
		WranglerEquivalent: "wrangler versions upload",
		Service: "workers", Scope: "version", Verb: "write",
		APIOps:      []string{"POST /accounts/{account_id}/workers/scripts/{script_name}/versions"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.versions.view", CLIPath: []string{"worker", "versions", "view"},
		WranglerEquivalent: "wrangler versions view",
		Service: "workers", Scope: "version", Verb: "read",
		APIOps:      []string{"GET /accounts/{account_id}/workers/scripts/{script_name}/versions/{version_id}"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.versions.deploy", CLIPath: []string{"worker", "versions", "deploy"},
		WranglerEquivalent: "wrangler versions deploy",
		Service: "workers", Scope: "version", Verb: "write",
		APIOps:      []string{"POST /accounts/{account_id}/workers/scripts/{script_name}/versions/{version_id}/deploy"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.versions.rollback", CLIPath: []string{"worker", "versions", "rollback"},
		WranglerEquivalent: "wrangler rollback",
		Service: "workers", Scope: "version", Verb: "write",
		APIOps:      []string{"POST /accounts/{account_id}/workers/scripts/{script_name}/versions/{version_id}/deploy"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.versions.delete", CLIPath: []string{"worker", "versions", "delete"},
		Service: "workers", Scope: "version", Verb: "delete",
		APIOps:      []string{"DELETE /accounts/{account_id}/workers/scripts/{script_name}/versions/{version_id}"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.deployments.list", CLIPath: []string{"worker", "deployments", "list"},
		WranglerEquivalent: "wrangler deployments list",
		Service: "workers", Scope: "deployment", Verb: "list",
		APIOps:      []string{"GET /accounts/{account_id}/workers/scripts/{script_name}/deployments"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "worker.deployments.view", CLIPath: []string{"worker", "deployments", "view"},
		WranglerEquivalent: "wrangler deployments view",
		Service: "workers", Scope: "deployment", Verb: "read",
		APIOps:      []string{"GET /accounts/{account_id}/workers/scripts/{script_name}/deployments/{deployment_id}"},
		Permissions: Permissions{Account: []string{"Workers Scripts"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},

	// --- kv namespaces ---
	{
		ID: "kv.namespace.create", CLIPath: []string{"kv", "namespace", "create"},
		WranglerEquivalent: "wrangler kv namespace create",
		Service: "kv", Scope: "namespace", Verb: "write",
		APIOps:      []string{"POST /accounts/{account_id}/storage/kv/namespaces"},
		Permissions: Permissions{Account: []string{"Workers KV Storage"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "kv.namespace.list", CLIPath: []string{"kv", "namespace", "list"},
		WranglerEquivalent: "wrangler kv namespace list",
		Service: "kv", Scope: "account", Verb: "list",
		APIOps:      []string{"GET /accounts/{account_id}/storage/kv/namespaces"},
		Permissions: Permissions{Account: []string{"Workers KV Storage"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "kv.namespace.delete", CLIPath: []string{"kv", "namespace", "delete"},
		WranglerEquivalent: "wrangler kv namespace delete",
		Service: "kv", Scope: "namespace", Verb: "delete",
		APIOps:      []string{"DELETE /accounts/{account_id}/storage/kv/namespaces/{namespace_id}"},
		Permissions: Permissions{Account: []string{"Workers KV Storage"}},
		APIChecks:   []string{"namespace_empty"},
		DangerLevel: "high", Destructive: true, Trackable: true,
	},

	// --- kv keys ---
	{
		ID: "kv.put", CLIPath: []string{"kv", "put"},
		WranglerEquivalent: "wrangler kv key put",
		Service: "kv", Scope: "key", Verb: "write",
		APIOps:      []string{"PUT /accounts/{account_id}/storage/kv/namespaces/{namespace_id}/values/{key}"},
		Permissions: Permissions{Account: []string{"Workers KV Storage"}},
		LocalChecks: []string{"key_charset"},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "kv.get", CLIPath: []string{"kv", "get"},
		WranglerEquivalent: "wrangler kv key get",
		Service: "kv", Scope: "key", Verb: "read",
		APIOps:      []string{"GET /accounts/{account_id}/storage/kv/namespaces/{namespace_id}/values/{key}"},
		Permissions: Permissions{Account: []string{"Workers KV Storage"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "kv.delete", CLIPath: []string{"kv", "delete"},
		WranglerEquivalent: "wrangler kv key delete",
		Service: "kv", Scope: "key", Verb: "delete",
		APIOps:      []string{"DELETE /accounts/{account_id}/storage/kv/namespaces/{namespace_id}/values/{key}"},
		Permissions: Permissions{Account: []string{"Workers KV Storage"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "kv.list", CLIPath: []string{"kv", "list"},
		WranglerEquivalent: "wrangler kv key list",
		Service: "kv", Scope: "namespace", Verb: "list",
		APIOps:      []string{"GET /accounts/{account_id}/storage/kv/namespaces/{namespace_id}/keys"},
		Permissions: Permissions{Account: []string{"Workers KV Storage"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},

	// --- d1 databases ---
	{
		ID: "d1.create", CLIPath: []string{"d1", "create"},
		WranglerEquivalent: "wrangler d1 create",
		Service: "d1", Scope: "database", Verb: "write",
		APIOps:      []string{"POST /accounts/{account_id}/d1/database"},
		Permissions: Permissions{Account: []string{"D1"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "d1.list", CLIPath: []string{"d1", "list"},
		WranglerEquivalent: "wrangler d1 list",
		Service: "d1", Scope: "account", Verb: "list",
		APIOps:      []string{"GET /accounts/{account_id}/d1/database"},
		Permissions: Permissions{Account: []string{"D1"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "d1.get", CLIPath: []string{"d1", "get"},
		WranglerEquivalent: "wrangler d1 info",
		Service: "d1", Scope: "database", Verb: "read",
		APIOps:      []string{"GET /accounts/{account_id}/d1/database/{database_id}"},
		Permissions: Permissions{Account: []string{"D1"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "d1.delete", CLIPath: []string{"d1", "delete"},
		WranglerEquivalent: "wrangler d1 delete",
		Service: "d1", Scope: "database", Verb: "delete",
		APIOps:      []string{"DELETE /accounts/{account_id}/d1/database/{database_id}"},
		Permissions: Permissions{Account: []string{"D1"}},
		DangerLevel: "high", Destructive: true, Trackable: true,
	},
	{
		ID: "d1.query", CLIPath: []string{"d1", "query"},
		WranglerEquivalent: "wrangler d1 query",
		Service: "d1", Scope: "database", Verb: "write",
		APIOps:      []string{"POST /accounts/{account_id}/d1/database/{database_id}/query"},
		Permissions: Permissions{Account: []string{"D1"}},
		LocalChecks: []string{"unbounded_delete_guard"},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "d1.import", CLIPath: []string{"d1", "import"},
		WranglerEquivalent: "wrangler d1 import",
		Service: "d1", Scope: "database", Verb: "write",
		APIOps:      []string{"POST /accounts/{account_id}/d1/database/{database_id}/import"},
		Permissions: Permissions{Account: []string{"D1"}},
		LocalChecks: []string{"dump_file_readable"},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "d1.export", CLIPath: []string{"d1", "export"},
		WranglerEquivalent: "wrangler d1 export",
		Service: "d1", Scope: "database", Verb: "read",
		APIOps:      []string{"POST /accounts/{account_id}/d1/database/{database_id}/export"},
		Permissions: Permissions{Account: []string{"D1"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "d1.migrations.list", CLIPath: []string{"d1", "migrations", "list"},
		WranglerEquivalent: "wrangler d1 migrations list",
		Service: "d1", Scope: "database", Verb: "list",
		APIOps:      []string{"GET /accounts/{account_id}/d1/database/{database_id}/query"},
		Permissions: Permissions{Account: []string{"D1"}},
		LocalChecks: []string{"migrations_dir_present"},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "d1.migrations.create", CLIPath: []string{"d1", "migrations", "create"},
		WranglerEquivalent: "wrangler d1 migrations create",
		Service: "d1", Scope: "database", Verb: "write",
		Permissions: Permissions{Account: []string{"D1"}},
		LocalChecks: []string{"migrations_dir_writable"},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "d1.migrations.apply", CLIPath: []string{"d1", "migrations", "apply"},
		WranglerEquivalent: "wrangler d1 migrations apply",
		Service: "d1", Scope: "database", Verb: "write",
		APIOps:      []string{"POST /accounts/{account_id}/d1/database/{database_id}/query"},
		Permissions: Permissions{Account: []string{"D1"}},
		LocalChecks: []string{"migrations_dir_present"},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "d1.time-travel.restore", CLIPath: []string{"d1", "time-travel", "restore"},
		WranglerEquivalent: "wrangler d1 time-travel restore",
		Service: "d1", Scope: "database", Verb: "write",
		APIOps: []string{
			"GET /accounts/{account_id}/d1/database/{database_id}/time_travel/bookmark",
			"POST /accounts/{account_id}/d1/database/{database_id}/restore",
		},
		Permissions: Permissions{Account: []string{"D1"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},

	// --- dns records (zone-scoped) ---
	{
		ID: "dns.create", CLIPath: []string{"dns", "create"},
		Service: "dns", Scope: "record", Verb: "write",
		APIOps:      []string{"POST /zones/{zone_id}/dns_records"},
		Permissions: Permissions{Zone: []string{"DNS"}},
		LocalChecks: []string{"record_type_known", "record_content_valid"},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "dns.list", CLIPath: []string{"dns", "list"},
		Service: "dns", Scope: "zone", Verb: "list",
		APIOps:      []string{"GET /zones/{zone_id}/dns_records"},
		Permissions: Permissions{Zone: []string{"DNS"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "dns.get", CLIPath: []string{"dns", "get"},
		Service: "dns", Scope: "record", Verb: "read",
		APIOps:      []string{"GET /zones/{zone_id}/dns_records/{record_id}"},
		Permissions: Permissions{Zone: []string{"DNS"}},
		DangerLevel: "low", Destructive: false, Trackable: true,
	},
	{
		ID: "dns.update", CLIPath: []string{"dns", "update"},
		Service: "dns", Scope: "record", Verb: "write",
		APIOps:      []string{"PUT /zones/{zone_id}/dns_records/{record_id}"},
		Permissions: Permissions{Zone: []string{"DNS"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
	{
		ID: "dns.delete", CLIPath: []string{"dns", "delete"},
		Service: "dns", Scope: "record", Verb: "delete",
		APIOps:      []string{"DELETE /zones/{zone_id}/dns_records/{record_id}"},
		Permissions: Permissions{Zone: []string{"DNS"}},
		DangerLevel: "medium", Destructive: false, Trackable: true,
	},
}
